version: "3"

services:

  arcgraphql:
    image: krautzera/nodedev:latest
    ports:
      - "10002:22"
    volumes:
      - "/root/devhome:/root"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  redditmediator:
    image: krautzera/godev:latest
    ports:
      - "10001:22"
    volumes:
      - "/root/devhome:/root"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
