version: "3"

services:

  redditmediator:
    image: "krautzera/redditmediator:0.2.0"
    container_name: "redditmediator"
    expose:
      - "80"
    environment:
      - REDDIT_MEDIATOR_USER_USERNAME
      - REDDIT_MEDIATOR_USER_PASSWORD
      - REDDIT_MEDIATOR_APP_ID
      - REDDIT_MEDIATOR_APP_SECRET
    labels:
     - "traefik.frontend.rule=PathPrefixStrip:/redditmediator"

  traefik:
    image: "traefik:v1.7.19"
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--api"
      - "--docker"
      - "--logLevel=DEBUG"
    volumes:
      - "./config/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
